"""empty message

Revision ID: 11b1acb4d578
Revises: 9921faef72a0
Create Date: 2020-04-08 16:14:38.946502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b1acb4d578'
down_revision = '9921faef72a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dl_history', sa.Column('file_id', sa.Integer(), nullable=False))
    op.drop_constraint('dl_history_course_id_fkey', 'dl_history', type_='foreignkey')
    op.create_foreign_key(None, 'dl_history', 'file_info', ['file_id'], ['file_id'])
    op.drop_column('dl_history', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dl_history', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dl_history', type_='foreignkey')
    op.create_foreign_key('dl_history_course_id_fkey', 'dl_history', 'course_info', ['course_id'], ['course_id'])
    op.drop_column('dl_history', 'file_id')
    # ### end Alembic commands ###
