"""empty message

Revision ID: 4b4931b5d2f2
Revises: 
Create Date: 2020-04-08 12:18:16.001342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4931b5d2f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_info',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=6), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('prof_info',
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('prof_email', sa.String(length=80), nullable=False),
    sa.Column('prof_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('prof_id'),
    sa.UniqueConstraint('prof_email'),
    sa.UniqueConstraint('prof_name')
    )
    op.create_table('user_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_prof',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_info.course_id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['prof_info.prof_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'prof_id')
    )
    op.create_table('file_info',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('prof_name', sa.String(length=200), nullable=False),
    sa.Column('course_term', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_info.course_id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['prof_info.prof_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('review_info',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.String(length=2048), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_info.file_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_info')
    op.drop_table('file_info')
    op.drop_table('course_prof')
    op.drop_table('user_info')
    op.drop_table('prof_info')
    op.drop_table('course_info')
    # ### end Alembic commands ###
