"""empty message

Revision ID: 9921faef72a0
Revises: 4b4931b5d2f2
Create Date: 2020-04-08 15:54:23.121295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9921faef72a0'
down_revision = '4b4931b5d2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_info.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.drop_constraint('prof_info_prof_email_key', 'prof_info', type_='unique')
    op.drop_column('prof_info', 'prof_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof_info', sa.Column('prof_email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('prof_info_prof_email_key', 'prof_info', ['prof_email'])
    op.drop_table('dl_history')
    # ### end Alembic commands ###
