"""empty message

Revision ID: bdca6c6257ff
Revises: 7f394938a766
Create Date: 2020-03-22 17:46:27.015780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdca6c6257ff'
down_revision = '7f394938a766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_info',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=6), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('prof_info',
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('prof_email', sa.String(length=80), nullable=False),
    sa.Column('prof_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('prof_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prof_info')
    op.drop_table('course_info')
    # ### end Alembic commands ###
