"""empty message

Revision ID: c5cc3b4d8034
Revises: e9e3e115d850
Create Date: 2020-03-20 17:25:13.191681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cc3b4d8034'
down_revision = 'e9e3e115d850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_info', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review_info', 'file_info', ['file_id'], ['file_ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_info', type_='foreignkey')
    op.drop_column('review_info', 'file_id')
    # ### end Alembic commands ###
